services:
  # Main application
  app:
    container_name: trade_bot-app
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=trade_bot-redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./static:/app/static
    networks:
      - tradebot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery worker for background tasks
  celery-worker:
    container_name: trade_bot-worker
    build: .
    command: celery -A app.tasks.daily_tasks worker --loglevel=info --concurrency=2
    environment:
      - REDIS_HOST=trade_bot-redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      - redis
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./static:/app/static
    networks:
      - tradebot-network
    restart: unless-stopped

  # Celery beat scheduler
  celery-beat:
    container_name: trade_bot-beat
    build: .
    command: celery -A app.tasks.daily_tasks beat --loglevel=info
    environment:
      - REDIS_HOST=trade_bot-redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      - redis
      - celery-worker
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./static:/app/static
    networks:
      - tradebot-network
    restart: unless-stopped

  # Redis for caching and Celery broker
  redis:
    container_name: trade_bot-redis
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - tradebot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  flower:
    container_name: trade_bot-flower
    build: .
    command: celery -A app.tasks.daily_tasks flower --port=5555 --address=0.0.0.0
    ports:
      - "5555:5555"
    environment:
      - REDIS_HOST=trade_bot-redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - celery-worker
    networks:
      - tradebot-network
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  tradebot-network:
    driver: bridge
