services:
  # Main application
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      - opensearch
      - redis
    volumes:
      - ./app:/app/app
    networks:
      - tradebot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery worker for background tasks
  celery-worker:
    build: .
    command: celery -A app.tasks.daily_tasks worker --loglevel=info --concurrency=2
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      - redis
      - opensearch
    volumes:
      - ./app:/app/app
    networks:
      - tradebot-network
    restart: unless-stopped

  # Celery beat scheduler
  celery-beat:
    build: .
    command: celery -A app.tasks.daily_tasks beat --loglevel=info
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALPHA_VANTAGE_KEY=${ALPHA_VANTAGE_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
    depends_on:
      - redis
      - celery-worker
    volumes:
      - ./app:/app/app
    networks:
      - tradebot-network
    restart: unless-stopped

  # OpenSearch for data storage
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
    ports:
      - "9201:9200"
      - "9601:9600"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - tradebot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis for caching and Celery broker
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - tradebot-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  flower:
    build: .
    command: celery -A app.tasks.daily_tasks flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - celery-worker
    networks:
      - tradebot-network
    restart: unless-stopped
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch
    networks:
      - tradebot-network
    restart: unless-stopped

volumes:
  opensearch_data:
    driver: local
  redis_data:
    driver: local

networks:
  tradebot-network:
    driver: bridge
